import type { Metadata } from "next";
import Carousel from "../components/Carousel";
import About from "../components/About";
import Cards from "../components/Cards";
import ImgGallery from "../components/ImgGallery";

export const metadata: Metadata = {
  title: "Museu Tecnológico",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <main className="flex-grow">
      <Carousel />
      <About />
      <Cards />
      <ImgGallery />
    </main>
  );
}